import { Room, RoomEvent } from "livekit-client";

/**
 * Akool — TEXT mode, and that difference is the whole story.
 *
 * Akool's live avatar has no audio input. You cannot hand it PCM and ask it to
 * lip-sync; you send chat text over the stream and Akool speaks it with its own
 * `voice_id`. So selecting Akool silently replaces the Arabic voice this project
 * ranked in SCORING.md Step 1 with whatever voice the Akool avatar carries.
 *
 * That makes Akool a different experiment, not a third data point in the same one:
 * comparing its lip-sync to Anam's means comparing two different voices at the same
 * time, which is precisely the confound Phase 0 avoided by rendering fixture audio
 * once and feeding identical files to every renderer. The admin page says this in
 * plain language rather than leaving an operator to discover it live.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * PARTLY VERIFIED against a live key on 2026-08-11 (npm run check:akool):
 *
 *   ✓ session/create returns credentials named `livekit_url` and `livekit_token`
 *     — the namespaced spelling this adapter reads, alongside livekit_room_name,
 *     livekit_client_identity and livekit_server_identity.
 *   ✓ session/close is accepted, so a session can be ended on demand.
 *
 *   ✓ the chat message shape reaches the avatar and makes it talk — confirmed at a
 *     live booth run, which also exposed the mode bug documented below.
 *
 *   ✗ STILL UNVERIFIED: the interrupt command, and whether retelling mode is
 *     reliably in force by the first sentence rather than merely usually.
 * ─────────────────────────────────────────────────────────────────────────────
 */

/**
 * Akool's two conversation modes, set per session with the `set-params` command.
 *
 * 1 = "retelling": the avatar speaks the text we send, verbatim.
 * 2 = "dialogue":  the text we send is treated as a message TO Akool's own LLM,
 *                  which composes its own reply and speaks that instead.
 *
 * The booth must be 1, and this is not a preference. Every answer has already been
 * generated by Claude against the Devoteam corpus, with citations and a grounding
 * check. In dialogue mode all of that is thrown away at the last step: Akool reads
 * our finished answer as if it were the visitor's question and improvises something
 * off its own general knowledge — which looks exactly like "the avatar is ignoring
 * the information file", because it is. Leaving the mode unset inherits Akool's
 * default, which is dialogue.
 */
const MODE_RETELLING = 1;

export function akoolAdapter() {
  return {
    mode: "text",
    room: null,
    /** Resolves once the avatar has joined AND been switched to retelling mode. */
    ready: null,
    /** Message counter. Date.now() alone collides when two sentences land in one ms. */
    seq: 0,

    /**
     * One JSON message onto the data channel, in Akool's v2 envelope.
     *
     * `extra` carries the fields that sit beside `type` rather than inside `pld` —
     * `idx` and `fin` on a chat message, which is how Akool reassembles a reply
     * streamed in parts. We always send a whole sentence, so fin is always true.
     */
    publish(type, pld, extra = {}) {
      const payload = { v: 2, type, mid: `msg-${Date.now()}-${this.seq++}`, ...extra, pld };
      this.room?.localParticipant?.publishData(
        new TextEncoder().encode(JSON.stringify(payload)),
        { reliable: true },
      );
    },

    /** Put this session into retelling mode. Safe to call repeatedly. */
    applyRetellingMode(log) {
      this.publish("command", { cmd: "set-params", data: { mode: MODE_RETELLING } });
      log("Akool set to retelling mode — it speaks our answer, not its own");
    },

    async connect(videoElementId, session, { log }) {
      // Akool namespaces the connection fields by transport: the LiveKit credentials
      // arrive as `livekit_url` / `livekit_token`, not the bare `url` / `token` this
      // adapter originally guessed at. Confirmed against a live session on 2026-08-11.
      // The bare spellings are kept as a fallback purely in case Akool ever flattens
      // the shape — a wrong guess here fails at connect time with an empty room and
      // no useful error, which is why the throw below names the fields it actually got.
      const c = session.credentials ?? {};
      const url = c.livekit_url ?? c.url;
      const token = c.livekit_token ?? c.token;
      if (!url || !token) {
        throw new Error(
          `Akool returned no LiveKit url/token — got fields: ${Object.keys(c).join(", ") || "(none)"}`,
        );
      }

      this.room = new Room();

      // Akool publishes the avatar as a normal WebRTC track pair.
      this.room.on(RoomEvent.TrackSubscribed, (track) => {
        const el = document.getElementById(videoElementId);
        if (track.kind === "video") track.attach(el);
        if (track.kind === "audio") track.attach(document.getElementById("avatar-audio"));
      });
      this.room.on(RoomEvent.Disconnected, () => log("Akool room disconnected"));

      // A command published into a room the avatar has not joined yet is delivered to
      // nobody and silently dropped — no ack, no error. So the mode switch waits for
      // the avatar to arrive, and is re-applied on every join afterwards. Re-applying
      // is idempotent and covers the case the timeout below cannot: an avatar that
      // turns up late, or a reconnect that quietly resets the session to dialogue.
      // Getting this wrong does not break the booth, it makes the booth improvise,
      // which is far harder to notice and far worse in front of a visitor.
      this.room.on(RoomEvent.ParticipantConnected, () => this.applyRetellingMode(log));

      const avatarPresent = new Promise((resolve) => {
        if (this.room.remoteParticipants.size) return resolve();
        this.room.once(RoomEvent.ParticipantConnected, () => resolve());
        // A booth that never finishes connecting is worse than one that sets the mode
        // a moment late, and the listener above still fixes the mode when it arrives.
        setTimeout(resolve, 8000);
      });

      await this.room.connect(url, token);

      this.ready = avatarPresent.then(() => this.applyRetellingMode(log));
      await this.ready;

      log("Akool ready (text mode — Akool's own voice)");
    },

    begin() {
      /* no audio sequence in text mode */
    },

    push() {
      // Guard rather than silently no-op: reaching here means the caller treated a
      // text-mode renderer as a PCM one, and the visitor would get a mute avatar.
      throw new Error("Akool is text mode — send text with say(), not PCM");
    },

    /**
     * Send one sentence for Akool to speak in its own voice.
     *
     * Queued behind `ready` so nothing is ever sent before the retelling-mode switch
     * lands: a sentence that overtakes it gets answered by Akool's LLM instead of
     * spoken, and the first sentence of a conversation is the one a visitor judges the
     * booth on. Chaining every call off the same promise preserves sentence order,
     * since handlers attached to one promise run in the order they were attached.
     */
    say(text) {
      Promise.resolve(this.ready).then(() =>
        this.publish("chat", { text }, { idx: 0, fin: true }),
      );
    },

    end() {
      /* nothing to close per utterance */
    },

    interrupt() {
      this.publish("command", { cmd: "interrupt" });
    },

    async disconnect() {
      await this.room?.disconnect();
      this.room = null;
      this.ready = null;
    },
  };
}
